### ISSUE TITLE
VQA: Mobile menu

### ISSUE THREAD

**Issue by jcreech83** [GoogleChrome/ioweb2016#189]
- [x] change cyan to 300: #4DD0E1
- [x] “may 18–20, 2016” and “Mountain View, CA” font color: #1E535A
- [x] close up the horizontal space between grey band behind home and top cyan block
- [x] “home” and “faq” and all subsequent menu items font color: #546E7A
