### ISSUE TITLE
Notifications: meta bug for sending notification types

### ISSUE THREAD

**Issue by nicolasgarnier** [GoogleChrome/ioweb2016#221]
Send for:
- [ ] -  a session in My Schedule is about to start
- [ ] - Videos of sessions added to My Schedule are available
- [ ] - provide feedback for a  session that's eneded in My Schedule - https://github.com/GoogleChrome/ioweb2016/issues/869

---

Each users who have enabled notifications on their Web clients have added WebPush information in their Firebase data. When a session is about to start we should send notifications to users who have notifications enabled and who have bookmarked a session.

Relevant user data in Firebase:

```
<DatabaseShard1Name>
    Users
        <uid>
            web_notifications_enabled: true|false
            web_push_subscriptions
                <crc32_endpoint>: {endpoint: <PushSubscription.endpoint>,keys: {p256dh: <PushSubscription.keys.p256dh>,auth: <PushSubscription.keys.auth>}}
            my_sessions
                <sessionUUID> : {timestamp:123456, bookmarked: true|false}
```
