### ISSUE TITLE
PWA Checklist

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/ioweb2016#34]
We should already be hitting most of these, but the sanity check is:
- [ ] fast first paint
- [x] app shell concept
- [x] service worker, offline
- [x] manifest bits, updates to it

And make sure everything is up to date (e.g. manifest updates + banner event).

For first paint, we may need to redo the I/O loading animation, use `body-bind`, or go async with imports. I have some tricks.
